//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Modelo", "UsuarioCupon", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CouponKing.Datos.Usuario), "Cupon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CouponKing.Datos.Cupon))]
[assembly: EdmRelationshipAttribute("Modelo", "TipoUsuarioUsuario", "TipoUsuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CouponKing.Datos.TipoUsuario), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CouponKing.Datos.Usuario))]

#endregion

namespace CouponKing.Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloContainer usando la cadena de conexión encontrada en la sección 'ModeloContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloContainer() : base("name=ModeloContainer", "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(string connectionString) : base(connectionString, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(EntityConnection connection) : base(connection, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cupon> Cupones
        {
            get
            {
                if ((_Cupones == null))
                {
                    _Cupones = base.CreateObjectSet<Cupon>("Cupones");
                }
                return _Cupones;
            }
        }
        private ObjectSet<Cupon> _Cupones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoUsuario> TipoUsuario
        {
            get
            {
                if ((_TipoUsuario == null))
                {
                    _TipoUsuario = base.CreateObjectSet<TipoUsuario>("TipoUsuario");
                }
                return _TipoUsuario;
            }
        }
        private ObjectSet<TipoUsuario> _TipoUsuario;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cupones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCupones(Cupon cupon)
        {
            base.AddObject("Cupones", cupon);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoUsuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoUsuario(TipoUsuario tipoUsuario)
        {
            base.AddObject("TipoUsuario", tipoUsuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Cupon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cupon : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cupon.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="nombre_Cupon">Valor inicial de la propiedad Nombre_Cupon.</param>
        /// <param name="tipo_Cupon">Valor inicial de la propiedad Tipo_Cupon.</param>
        public static Cupon CreateCupon(global::System.Int32 codigo, global::System.String nombre_Cupon, global::System.String tipo_Cupon)
        {
            Cupon cupon = new Cupon();
            cupon.Codigo = codigo;
            cupon.Nombre_Cupon = nombre_Cupon;
            cupon.Tipo_Cupon = tipo_Cupon;
            return cupon;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                if (_Codigo != value)
                {
                    OnCodigoChanging(value);
                    ReportPropertyChanging("Codigo");
                    _Codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Codigo");
                    OnCodigoChanged();
                }
            }
        }
        private global::System.Int32 _Codigo;
        partial void OnCodigoChanging(global::System.Int32 value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Cupon
        {
            get
            {
                return _Nombre_Cupon;
            }
            set
            {
                OnNombre_CuponChanging(value);
                ReportPropertyChanging("Nombre_Cupon");
                _Nombre_Cupon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre_Cupon");
                OnNombre_CuponChanged();
            }
        }
        private global::System.String _Nombre_Cupon;
        partial void OnNombre_CuponChanging(global::System.String value);
        partial void OnNombre_CuponChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo_Cupon
        {
            get
            {
                return _Tipo_Cupon;
            }
            set
            {
                OnTipo_CuponChanging(value);
                ReportPropertyChanging("Tipo_Cupon");
                _Tipo_Cupon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo_Cupon");
                OnTipo_CuponChanged();
            }
        }
        private global::System.String _Tipo_Cupon;
        partial void OnTipo_CuponChanging(global::System.String value);
        partial void OnTipo_CuponChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="TipoUsuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoUsuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoUsuario.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad Descripcion.</param>
        public static TipoUsuario CreateTipoUsuario(global::System.Int32 codigo, global::System.String descripcion)
        {
            TipoUsuario tipoUsuario = new TipoUsuario();
            tipoUsuario.Codigo = codigo;
            tipoUsuario.Descripcion = descripcion;
            return tipoUsuario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                if (_Codigo != value)
                {
                    OnCodigoChanging(value);
                    ReportPropertyChanging("Codigo");
                    _Codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Codigo");
                    OnCodigoChanged();
                }
            }
        }
        private global::System.Int32 _Codigo;
        partial void OnCodigoChanging(global::System.Int32 value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="codigo">Valor inicial de la propiedad Codigo.</param>
        /// <param name="cedula">Valor inicial de la propiedad Cedula.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        /// <param name="correo">Valor inicial de la propiedad Correo.</param>
        public static Usuario CreateUsuario(global::System.Int32 codigo, global::System.Int32 cedula, global::System.String nombre, global::System.String correo)
        {
            Usuario usuario = new Usuario();
            usuario.Codigo = codigo;
            usuario.Cedula = cedula;
            usuario.Nombre = nombre;
            usuario.Correo = correo;
            return usuario;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                if (_Codigo != value)
                {
                    OnCodigoChanging(value);
                    ReportPropertyChanging("Codigo");
                    _Codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Codigo");
                    OnCodigoChanged();
                }
            }
        }
        private global::System.Int32 _Codigo;
        partial void OnCodigoChanging(global::System.Int32 value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.Int32 _Cedula;
        partial void OnCedulaChanging(global::System.Int32 value);
        partial void OnCedulaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "UsuarioCupon", "Cupon")]
        public EntityCollection<Cupon> Cupones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cupon>("Modelo.UsuarioCupon", "Cupon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cupon>("Modelo.UsuarioCupon", "Cupon", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Modelo", "TipoUsuarioUsuario", "TipoUsuario")]
        public TipoUsuario TipoUsuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoUsuario>("Modelo.TipoUsuarioUsuario", "TipoUsuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoUsuario>("Modelo.TipoUsuarioUsuario", "TipoUsuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoUsuario> TipoUsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoUsuario>("Modelo.TipoUsuarioUsuario", "TipoUsuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoUsuario>("Modelo.TipoUsuarioUsuario", "TipoUsuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
